svg_icons:
  default: 'far-comment-dots|reply-all'
  type: 'list'
  list_type: 'compact'
pm_button_icon:
  default: 'fa-comment-dots'
  type: string
  description: "Icon to be used for the PM button"
reply_button_icon:
  default: 'reply'
  type: string
  description: "Icon to be used for the Reply button"
